/**
 * Hook för att generera förhandsvisnings-URL:er från app-URL:er
 * Använder WordPress mshots API (gratis, ingen API-nyckel krävs)
 */

export function getPreviewUrl(url: string, width = 1200, height = 630): string {
  const encoded = encodeURIComponent(url);
  return `https://s.wordpress.com/mshots/v1/${encoded}?w=${width}&h=${height}`;
}

export function isAutoGeneratedImage(imageUrl: string | undefined): boolean {
  return !!imageUrl && imageUrl.includes('s.wordpress.com/mshots');
}
