import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Loader2, Image, RefreshCw } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { ImageUploader } from '@/components/ImageUploader';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from '@/components/ui/form';
import { useCategories } from '@/hooks/useApps';
import { useSubmitApp } from '@/hooks/useSubmitApp';
import { getPreviewUrl, isAutoGeneratedImage } from '@/hooks/useUrlPreview';
import { toast } from 'sonner';

const formSchema = z.object({
  title: z.string().min(2, 'Titeln måste vara minst 2 tecken').max(100, 'Max 100 tecken'),
  url: z.string().url('Ange en giltig URL'),
  description: z.string().min(10, 'Beskrivningen måste vara minst 10 tecken').max(150, 'Max 150 tecken'),
  long_description: z.string().max(2000, 'Max 2000 tecken').optional(),
  image_url: z.string().optional(),
  categories: z.array(z.string()).min(1, 'Välj minst en kategori'),
});

type FormValues = z.infer<typeof formSchema>;

const MAX_RETRIES = 6;

export function AppCreatePanel() {
  const navigate = useNavigate();
  const { data: categories } = useCategories();
  const submitApp = useSubmitApp();

  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState(false);
  const [retryCount, setRetryCount] = useState(0);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: '',
      url: '',
      description: '',
      long_description: '',
      image_url: '',
      categories: [],
    },
  });

  // Auto-generate thumbnail when URL changes
  const watchedUrl = form.watch('url');
  useEffect(() => {
    if (watchedUrl && watchedUrl.startsWith('https://')) {
      setPreviewLoading(true);
      setPreviewError(false);
      setRetryCount(0);
      const currentImage = form.getValues('image_url');
      const isCustomImage = currentImage && !isAutoGeneratedImage(currentImage);
      if (!isCustomImage) {
        form.setValue('image_url', getPreviewUrl(watchedUrl));
      }
    }
  }, [watchedUrl, form]);

  // Polling effect for preview
  useEffect(() => {
    if (!previewLoading || retryCount >= MAX_RETRIES) {
      if (retryCount >= MAX_RETRIES && previewLoading) {
        setPreviewLoading(false);
        setPreviewError(true);
      }
      return;
    }

    const pollInterval = setInterval(() => {
      setRetryCount(prev => prev + 1);
    }, 5000);

    return () => clearInterval(pollInterval);
  }, [previewLoading, retryCount]);

  const onSubmit = async (values: FormValues) => {
    try {
      await submitApp.mutateAsync({
        title: values.title,
        url: values.url,
        description: values.description,
        long_description: values.long_description,
        image_url: values.image_url,
        categories: values.categories,
      });

      toast.success('App inskickad! 🎉', {
        description: 'Din app granskas nu och publiceras snart.',
      });
      navigate('/min-sida');
    } catch (error) {
      toast.error('Kunde inte skicka in appen');
    }
  };

  const groupedCategories = categories?.reduce((acc, cat) => {
    const type = cat.type || 'other';
    if (!acc[type]) acc[type] = [];
    acc[type].push(cat);
    return acc;
  }, {} as Record<string, typeof categories>);

  const typeLabels: Record<string, string> = {
    subject: 'Ämne',
    age: 'Ålder',
    type: 'Typ',
    other: 'Övrigt',
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-xl font-bold">Lägg till ny app</h1>
        <p className="text-sm text-muted-foreground">
          Dela en lärande app med andra föräldrar
        </p>
      </div>

      {/* Form */}
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          <FormField
            control={form.control}
            name="title"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Appens namn *</FormLabel>
                <FormControl>
                  <Input placeholder="t.ex. Khan Academy Kids" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="url"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Länk till appen *</FormLabel>
                <FormControl>
                  <Input placeholder="https://..." {...field} />
                </FormControl>
                <FormDescription>
                  Länk till appens hemsida, App Store eller Google Play
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Auto-generated thumbnail preview */}
          {watchedUrl && watchedUrl.startsWith('https://') && (
            <div className="space-y-3 p-4 rounded-lg bg-muted/50 border border-border">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-sm font-medium">
                  <Image className="h-4 w-4 text-primary" />
                  Automatisk thumbnail
                </div>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setPreviewLoading(true);
                    setRetryCount(0);
                    form.setValue('image_url', getPreviewUrl(watchedUrl));
                  }}
                  className="gap-1 text-xs"
                >
                  <RefreshCw className="h-3 w-3" />
                  Uppdatera
                </Button>
              </div>
              <div className="relative aspect-video rounded-md overflow-hidden bg-muted">
                {previewLoading && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center bg-muted z-10">
                    <Loader2 className="h-8 w-8 animate-spin text-primary" />
                    <p className="text-xs text-muted-foreground mt-2">
                      Laddar... ({retryCount + 1}/{MAX_RETRIES})
                    </p>
                  </div>
                )}
                {previewError && !previewLoading && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center bg-muted z-10 text-center p-4">
                    <Image className="h-8 w-8 text-muted-foreground mb-2" />
                    <p className="text-sm text-muted-foreground">
                      Kunde inte ladda förhandsvisning
                    </p>
                  </div>
                )}
                <img
                  key={retryCount}
                  src={`${getPreviewUrl(watchedUrl)}&retry=${retryCount}`}
                  alt="Förhandsvisning"
                  className={`w-full h-full object-cover transition-opacity ${previewLoading || previewError ? 'opacity-0' : 'opacity-100'}`}
                  onLoad={() => {
                    setPreviewLoading(false);
                    setPreviewError(false);
                  }}
                  onError={() => {
                    if (retryCount >= MAX_RETRIES - 1) {
                      setPreviewLoading(false);
                      setPreviewError(true);
                    }
                  }}
                />
              </div>
            </div>
          )}

          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Kort beskrivning *</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Beskriv appen kortfattat..."
                    className="resize-none h-20"
                    {...field}
                  />
                </FormControl>
                <p className="text-xs text-muted-foreground text-right">
                  {field.value?.length || 0}/150
                </p>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="long_description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Detaljerad beskrivning (valfritt)</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Beskriv appen mer utförligt..."
                    className="resize-none h-32"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Custom Image Upload */}
          <FormField
            control={form.control}
            name="image_url"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Egen bild (valfritt)</FormLabel>
                <FormControl>
                  <ImageUploader
                    value={field.value}
                    onChange={(url) => field.onChange(url || '')}
                  />
                </FormControl>
                <FormDescription>
                  Ladda upp en egen bild om du inte vill använda den automatiska
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Categories */}
          <FormField
            control={form.control}
            name="categories"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Kategorier *</FormLabel>
                <div className="space-y-4">
                  {groupedCategories && Object.entries(groupedCategories).map(([type, cats]) => (
                    <div key={type} className="space-y-2">
                      <p className="text-sm font-medium text-muted-foreground">
                        {typeLabels[type] || type}
                      </p>
                      <div className="flex flex-wrap gap-2">
                        {cats?.map((cat) => {
                          const isSelected = field.value.includes(cat.id);
                          return (
                            <label
                              key={cat.id}
                              className={`
                                flex items-center gap-2 px-3 py-1.5 rounded-full text-sm cursor-pointer transition-colors
                                ${isSelected
                                  ? 'bg-primary text-primary-foreground'
                                  : 'bg-muted hover:bg-muted/80'
                                }
                              `}
                            >
                              <Checkbox
                                checked={isSelected}
                                onCheckedChange={(checked) => {
                                  if (checked) {
                                    field.onChange([...field.value, cat.id]);
                                  } else {
                                    field.onChange(field.value.filter((id) => id !== cat.id));
                                  }
                                }}
                                className="hidden"
                              />
                              {cat.name}
                            </label>
                          );
                        })}
                      </div>
                    </div>
                  ))}
                </div>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Actions */}
          <div className="flex items-center justify-end gap-2 pt-4 border-t">
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate('/min-sida')}
            >
              Avbryt
            </Button>
            <Button
              type="submit"
              disabled={submitApp.isPending}
            >
              {submitApp.isPending && (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              )}
              Skicka in app
            </Button>
          </div>
        </form>
      </Form>
    </div>
  );
}
