import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, ArrowRight, Check, Loader2, Globe, FileText, Tags, Eye, Image, RefreshCw } from 'lucide-react';
import { getPreviewUrl, isAutoGeneratedImage } from '@/hooks/useUrlPreview';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage, FormDescription } from '@/components/ui/form';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ImageUploader } from './ImageUploader';
import { useCategories } from '@/hooks/useApps';
import { useSubmitApp } from '@/hooks/useSubmitApp';
import { useUpdateApp } from '@/hooks/useEditApp';
import { toast } from '@/hooks/use-toast';

const formSchema = z.object({
  title: z.string().min(3, 'Titel måste vara minst 3 tecken').max(100, 'Titel får max vara 100 tecken'),
  url: z.string().url('Ange en giltig URL (börja med https://)'),
  description: z.string().min(10, 'Beskrivning måste vara minst 10 tecken').max(200, 'Kort beskrivning får max vara 200 tecken'),
  long_description: z.string().max(2000, 'Lång beskrivning får max vara 2000 tecken').optional(),
  image_url: z.string().optional(),
  categories: z.array(z.string()).min(1, 'Välj minst en kategori')
});

type FormData = z.infer<typeof formSchema>;

const steps = [
  { id: 1, title: 'Grundinfo', icon: Globe, description: 'Namn och länk' },
  { id: 2, title: 'Kategorier', icon: Tags, description: 'Ämne, ålder & typ' },
  { id: 3, title: 'Detaljer', icon: FileText, description: 'Bild & beskrivning' },
  { id: 4, title: 'Granska', icon: Eye, description: 'Förhandsvisning' }
];

interface SubmitWizardProps {
  mode?: 'create' | 'edit';
  appId?: string;
  initialData?: {
    title: string;
    url: string;
    description: string;
    long_description?: string | null;
    image_url?: string | null;
    categories: string[];
  };
}

export function SubmitWizard({ mode = 'create', appId, initialData }: SubmitWizardProps) {
  const [currentStep, setCurrentStep] = useState(1);
  const [previewLoading, setPreviewLoading] = useState(false);
  const navigate = useNavigate();
  const { data: categories = [] } = useCategories();
  const submitMutation = useSubmitApp();
  const updateMutation = useUpdateApp();

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: initialData?.title || '',
      url: initialData?.url || '',
      description: initialData?.description || '',
      long_description: initialData?.long_description || '',
      image_url: initialData?.image_url || '',
      categories: initialData?.categories || []
    }
  });

  // Reset form when initialData changes (for edit mode)
  useEffect(() => {
    if (initialData) {
      form.reset({
        title: initialData.title,
        url: initialData.url,
        description: initialData.description,
        long_description: initialData.long_description || '',
        image_url: initialData.image_url || '',
        categories: initialData.categories
      });
    }
  }, [initialData, form]);

  // Auto-generate thumbnail when URL changes
  const watchedUrl = form.watch('url');
  useEffect(() => {
    if (watchedUrl && watchedUrl.startsWith('https://')) {
      setPreviewLoading(true);
      // Auto-set preview URL if no custom image is uploaded
      const currentImage = form.getValues('image_url');
      const isCustomImage = currentImage && !isAutoGeneratedImage(currentImage);
      if (!isCustomImage) {
        form.setValue('image_url', getPreviewUrl(watchedUrl));
      }
      // Timeout fallback - stop loading after 10 seconds
      const timeout = setTimeout(() => {
        setPreviewLoading(false);
      }, 10000);
      return () => clearTimeout(timeout);
    }
  }, [watchedUrl, form]);

  const subjectCategories = categories.filter(c => c.type === 'subject');
  const ageCategories = categories.filter(c => c.type === 'age');
  const typeCategories = categories.filter(c => c.type === 'type');

  const validateStep = async (step: number) => {
    switch (step) {
      case 1:
        return form.trigger(['title', 'url', 'description']);
      case 2:
        return form.trigger(['categories']);
      case 3:
        return true;
      default:
        return true;
    }
  };

  const nextStep = async () => {
    const isValid = await validateStep(currentStep);
    if (isValid) {
      setCurrentStep(prev => Math.min(prev + 1, 4));
    }
  };

  const prevStep = () => {
    setCurrentStep(prev => Math.max(prev - 1, 1));
  };

  const isEditing = mode === 'edit';
  const mutation = isEditing ? updateMutation : submitMutation;

  const onSubmit = async (data: FormData) => {
    try {
      if (isEditing && appId) {
        await updateMutation.mutateAsync({
          appId,
          data: {
            title: data.title,
            url: data.url,
            description: data.description,
            long_description: data.long_description,
            image_url: data.image_url,
            categories: data.categories
          }
        });
        toast({
          title: 'App uppdaterad! ✨',
          description: 'Dina ändringar har sparats.'
        });
      } else {
        await submitMutation.mutateAsync({
          title: data.title,
          url: data.url,
          description: data.description,
          long_description: data.long_description,
          image_url: data.image_url,
          categories: data.categories
        });
        toast({
          title: 'App inskickad! 🎉',
          description: 'Din app granskas nu av vårt team och publiceras snart.'
        });
      }
      navigate('/min-sida');
    } catch (error) {
      toast({
        title: 'Något gick fel',
        description: 'Kunde inte skicka in appen, försök igen',
        variant: 'destructive'
      });
    }
  };

  const formValues = form.watch();
  const selectedCategories = categories.filter(c => formValues.categories.includes(c.id));

  return (
    <div className="max-w-3xl mx-auto">
      {/* Progress Steps */}
      <div className="mb-8">
        <div className="flex justify-between">
          {steps.map((step, index) => (
            <div key={step.id} className="flex-1 relative">
              <div className="flex flex-col items-center">
                <div className={`
                  w-12 h-12 rounded-full flex items-center justify-center transition-all duration-300
                  ${currentStep >= step.id 
                    ? 'bg-primary text-primary-foreground shadow-lg shadow-primary/30' 
                    : 'bg-muted text-muted-foreground'
                  }
                `}>
                  {currentStep > step.id ? (
                    <Check className="h-5 w-5" />
                  ) : (
                    <step.icon className="h-5 w-5" />
                  )}
                </div>
                <div className="mt-2 text-center hidden sm:block">
                  <p className={`text-sm font-medium ${currentStep >= step.id ? 'text-foreground' : 'text-muted-foreground'}`}>
                    {step.title}
                  </p>
                  <p className="text-xs text-muted-foreground">{step.description}</p>
                </div>
              </div>
              {index < steps.length - 1 && (
                <div className={`
                  absolute top-6 left-[calc(50%+24px)] right-[calc(-50%+24px)] h-0.5 transition-all duration-300
                  ${currentStep > step.id ? 'bg-primary' : 'bg-muted'}
                `} />
              )}
            </div>
          ))}
        </div>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)}>
          {/* Step 1: Basic Info */}
          {currentStep === 1 && (
            <Card className="border-2 border-primary/20">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Globe className="h-5 w-5 text-primary" />
                  Grundläggande information
                </CardTitle>
                <CardDescription>
                  Berätta om appen du vill dela med andra föräldrar
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <FormField
                  control={form.control}
                  name="title"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Appens namn *</FormLabel>
                      <FormControl>
                        <Input placeholder="t.ex. Khan Academy Kids" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="url"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Länk till appen *</FormLabel>
                      <FormControl>
                        <Input placeholder="https://..." {...field} />
                      </FormControl>
                      <FormDescription>
                        Länk till appens hemsida, App Store eller Google Play
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Auto-generate thumbnail preview */}
                {form.watch('url') && form.watch('url').startsWith('https://') && (
                  <div className="space-y-3 p-4 rounded-lg bg-muted/50 border border-border">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <Image className="h-4 w-4 text-primary" />
                        Automatisk thumbnail
                      </div>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        onClick={() => {
                          setPreviewLoading(true);
                          // Force refresh by adding timestamp
                          const previewUrl = getPreviewUrl(form.watch('url') + '?t=' + Date.now());
                          form.setValue('image_url', getPreviewUrl(form.watch('url')));
                        }}
                        className="gap-1 text-xs"
                      >
                        <RefreshCw className="h-3 w-3" />
                        Uppdatera
                      </Button>
                    </div>
                    <div className="relative aspect-video rounded-md overflow-hidden bg-muted">
                      {previewLoading && (
                        <div className="absolute inset-0 flex items-center justify-center bg-muted z-10">
                          <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        </div>
                      )}
                      <img
                        src={getPreviewUrl(form.watch('url'))}
                        alt="Förhandsvisning"
                        className={`w-full h-full object-cover transition-opacity ${previewLoading ? 'opacity-0' : 'opacity-100'}`}
                        onLoad={() => setPreviewLoading(false)}
                        onError={(e) => {
                          setPreviewLoading(false);
                          e.currentTarget.style.display = 'none';
                        }}
                      />
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Klicka "Hämta bild" för att använda denna som appens thumbnail. Du kan byta till egen bild i steg 3.
                    </p>
                  </div>
                )}

                <FormField
                  control={form.control}
                  name="description"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Kort beskrivning *</FormLabel>
                      <FormControl>
                        <Textarea 
                          placeholder="Beskriv appen kort - vad gör den bra för barn?" 
                          className="resize-none"
                          rows={3}
                          {...field} 
                        />
                      </FormControl>
                      <FormDescription>
                        {field.value?.length || 0}/200 tecken
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>
          )}

          {/* Step 2: Categories */}
          {currentStep === 2 && (
            <Card className="border-2 border-primary/20">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Tags className="h-5 w-5 text-primary" />
                  Kategorisera appen
                </CardTitle>
                <CardDescription>
                  Hjälp andra föräldrar hitta appen genom att välja rätt kategorier
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-8">
                <FormField
                  control={form.control}
                  name="categories"
                  render={({ field }) => (
                    <FormItem>
                      <div className="space-y-6">
                        {/* Subject Categories */}
                        <div>
                          <FormLabel className="text-base">Ämne</FormLabel>
                          <p className="text-sm text-muted-foreground mb-3">Vad lär sig barnet?</p>
                          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                            {subjectCategories.map(category => (
                              <label
                                key={category.id}
                                className={`
                                  flex items-center gap-2 p-3 rounded-lg border-2 cursor-pointer transition-all
                                  ${field.value.includes(category.id)
                                    ? 'border-primary bg-primary/10'
                                    : 'border-muted hover:border-primary/50'
                                  }
                                `}
                              >
                                <Checkbox
                                  checked={field.value.includes(category.id)}
                                  onCheckedChange={(checked) => {
                                    const newValue = checked
                                      ? [...field.value, category.id]
                                      : field.value.filter(id => id !== category.id);
                                    field.onChange(newValue);
                                  }}
                                />
                                <span className="text-sm">{category.icon} {category.name}</span>
                              </label>
                            ))}
                          </div>
                        </div>

                        {/* Age Categories */}
                        <div>
                          <FormLabel className="text-base">Åldersgrupp</FormLabel>
                          <p className="text-sm text-muted-foreground mb-3">Vilka åldrar passar appen för?</p>
                          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                            {ageCategories.map(category => (
                              <label
                                key={category.id}
                                className={`
                                  flex items-center gap-2 p-3 rounded-lg border-2 cursor-pointer transition-all
                                  ${field.value.includes(category.id)
                                    ? 'border-primary bg-primary/10'
                                    : 'border-muted hover:border-primary/50'
                                  }
                                `}
                              >
                                <Checkbox
                                  checked={field.value.includes(category.id)}
                                  onCheckedChange={(checked) => {
                                    const newValue = checked
                                      ? [...field.value, category.id]
                                      : field.value.filter(id => id !== category.id);
                                    field.onChange(newValue);
                                  }}
                                />
                                <span className="text-sm">{category.icon} {category.name}</span>
                              </label>
                            ))}
                          </div>
                        </div>

                        {/* Type Categories */}
                        <div>
                          <FormLabel className="text-base">Typ av app</FormLabel>
                          <p className="text-sm text-muted-foreground mb-3">Hur fungerar appen?</p>
                          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                            {typeCategories.map(category => (
                              <label
                                key={category.id}
                                className={`
                                  flex items-center gap-2 p-3 rounded-lg border-2 cursor-pointer transition-all
                                  ${field.value.includes(category.id)
                                    ? 'border-primary bg-primary/10'
                                    : 'border-muted hover:border-primary/50'
                                  }
                                `}
                              >
                                <Checkbox
                                  checked={field.value.includes(category.id)}
                                  onCheckedChange={(checked) => {
                                    const newValue = checked
                                      ? [...field.value, category.id]
                                      : field.value.filter(id => id !== category.id);
                                    field.onChange(newValue);
                                  }}
                                />
                                <span className="text-sm">{category.icon} {category.name}</span>
                              </label>
                            ))}
                          </div>
                        </div>
                      </div>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>
          )}

          {/* Step 3: Details */}
          {currentStep === 3 && (
            <Card className="border-2 border-primary/20">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  Lägg till detaljer
                </CardTitle>
                <CardDescription>
                  Lägg till en bild och mer information (valfritt)
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <FormField
                  control={form.control}
                  name="image_url"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Bild/Screenshot</FormLabel>
                      
                      {/* Show auto-generated image if present */}
                      {field.value && isAutoGeneratedImage(field.value) ? (
                        <div className="space-y-3">
                          <div className="relative aspect-video rounded-lg overflow-hidden border-2 border-primary/20 bg-muted">
                            <img
                              src={field.value}
                              alt="Automatiskt genererad"
                              className="w-full h-full object-cover"
                            />
                            <div className="absolute top-2 left-2">
                              <Badge variant="secondary" className="bg-background/80 backdrop-blur-sm">
                                Automatiskt genererad
                              </Badge>
                            </div>
                          </div>
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => field.onChange(undefined)}
                            className="w-full"
                          >
                            Ladda upp egen bild istället
                          </Button>
                        </div>
                      ) : (
                        <FormControl>
                          <ImageUploader
                            value={field.value}
                            onChange={field.onChange}
                          />
                        </FormControl>
                      )}
                      
                      <FormDescription>
                        {isAutoGeneratedImage(field.value) 
                          ? 'En förhandsvisning genererades automatiskt från appens URL'
                          : 'Ladda upp en screenshot eller logotyp för appen'
                        }
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="long_description"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Längre beskrivning (valfritt)</FormLabel>
                      <FormControl>
                        <Textarea 
                          placeholder="Berätta mer om appen - varför gillar ditt barn den? Vad är bra och vad kunde vara bättre?" 
                          className="resize-none"
                          rows={6}
                          {...field} 
                        />
                      </FormControl>
                      <FormDescription>
                        {field.value?.length || 0}/2000 tecken
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>
          )}

          {/* Step 4: Preview */}
          {currentStep === 4 && (
            <Card className="border-2 border-primary/20">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Eye className="h-5 w-5 text-primary" />
                  Granska innan du skickar
                </CardTitle>
                <CardDescription>
                  Kontrollera att allt ser rätt ut
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="rounded-xl border-2 border-muted overflow-hidden bg-card">
                  {formValues.image_url && (
                    <img 
                      src={formValues.image_url} 
                      alt={formValues.title}
                      className="w-full h-48 object-cover"
                    />
                  )}
                  <div className="p-6 space-y-4">
                    <div>
                      <h3 className="text-xl font-bold">{formValues.title || 'Appens namn'}</h3>
                      <a 
                        href={formValues.url} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="text-sm text-primary hover:underline"
                      >
                        {formValues.url || 'https://...'}
                      </a>
                    </div>
                    
                    <p className="text-muted-foreground">
                      {formValues.description || 'Kort beskrivning...'}
                    </p>

                    {formValues.long_description && (
                      <p className="text-sm text-muted-foreground border-t border-muted pt-4">
                        {formValues.long_description}
                      </p>
                    )}

                    <div className="flex flex-wrap gap-2 pt-2">
                      {selectedCategories.map(cat => (
                        <Badge key={cat.id} variant="secondary">
                          {cat.icon} {cat.name}
                        </Badge>
                      ))}
                    </div>
                  </div>
                </div>

                <div className="mt-6 p-4 rounded-lg bg-amber-500/10 border border-amber-500/20">
                  <p className="text-sm text-amber-700 dark:text-amber-300">
                    <strong>OBS:</strong> Din app kommer granskas av vårt team innan den publiceras. 
                    Detta brukar ta 1-2 dagar.
                  </p>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Navigation Buttons */}
          <div className="flex justify-between mt-8">
            <Button
              type="button"
              variant="outline"
              onClick={prevStep}
              disabled={currentStep === 1}
              className="gap-2"
            >
              <ArrowLeft className="h-4 w-4" />
              Tillbaka
            </Button>

            {currentStep < 4 ? (
              <Button
                type="button"
                onClick={nextStep}
                className="gap-2"
              >
                Nästa
                <ArrowRight className="h-4 w-4" />
              </Button>
            ) : (
              <Button
                type="submit"
                disabled={mutation.isPending}
                className="gap-2 bg-gradient-to-r from-primary to-secondary hover:opacity-90"
              >
                {mutation.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    {isEditing ? 'Sparar...' : 'Skickar...'}
                  </>
                ) : (
                  <>
                    <Check className="h-4 w-4" />
                    {isEditing ? 'Spara ändringar' : 'Skicka in app'}
                  </>
                )}
              </Button>
            )}
          </div>
        </form>
      </Form>
    </div>
  );
}
